### ISSUE TITLE
Leaving Website lightbox

### ISSUE THREAD

**Issue by s-melanson** [jmdrapeau/cws_R#18]
You do the functionality and then I'll style it.

**Comment by s-melanson** [comment]
![uploads/e341e165-3669-4462-9dee-9a025ccb1352/leaving-website.jpg](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fe341e165-3669-4462-9dee-9a025ccb1352%2Fleaving-website.jpg)

**Comment by jmdrapeau** [comment]
I added the lightbox in footer.php and created style on #leaving_site.

Don't rename the IDs or Classes as they are used in script.

**Comment by s-melanson** [comment]
all done. Your challenge is to activate the "blur" class in the site parent div

**Comment by jmdrapeau** [comment]
Blur has been added.  Your challenge it to find one that works outside of Firefox.
