### ISSUE TITLE
Style Search Results page

### ISSUE THREAD

**Issue by jmdrapeau** [jmdrapeau/cws_R#22]
Download psd and style accordingly.
https://mailtrack.io/trace/link/bb3ee2172cbfd1b6f7dfe37c3bbe9f0218d36a02?url=https%3A%2F%2Fwww.dropbox.com%2Fs%2Fsgkax8yapin6wcq%2FRM-SearchResults.psd%3Fdl%3D0&signature=04d2f1c5e6e2e900

**Comment by s-melanson** [comment]
styled. please add paging buttons at the bottom.

**Comment by jmdrapeau** [comment]
Added the pagination.  Search for Ridgemont and view source to get classes generated by WordPress.

I made each page 2 posts long in order to get multiple numbers to show up.

**Comment by s-melanson** [comment]
Done but do a search on "and" to see when there are 7 pages. There is an extra box "..." that is not clickable between 6 and 7... Like this: 

PREV 1  2  3  4  5  6  ...  7  NEXT
