### ISSUE TITLE
Hotdog mobile menu

### ISSUE THREAD

**Issue by jmdrapeau** [jmdrapeau/cws_R#8]
add code for responsive menu

**Comment by jmdrapeau** [comment]
Added an additional menu in WordPress > Appearance > Menus for Main Menu - Mobile.

HTML is in include-top-nav > last 3 lines.

SCSS look for master-nav-mobile and surrounding classes in media queries.

**Comment by s-melanson** [comment]
Not sure if I did everything you wanted here. Please double check the menu to make sure. :)

**Comment by s-melanson** [comment]
Also, please check that the menu works on mobile if it expands beyond the chrome (on the mobile browser testing it wasn't scrolling)
